services:
  - type: web
    name: outline
    env: docker
    repo: https://github.com/ryco-io/outline.git
    region: oregon
    plan: starter
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false  # Use secret from Render
      - key: REDIS_URL
        value: redis://outline-redis:6379
      - key: URL
        value: https://outline-kwps.onrender.com
      - key: PORT
        value: 3000
      - key: FORCE_HTTPS
        value: "true"

  - type: worker
    name: outline-redis
    env: docker
    dockerfilePath: ./redis.Dockerfile
    plan: starter
