services:
  - type: web
    name: outline
    env: docker
    repo: https://github.com/ryco-io/outline.git
    region: oregon
    plan: standard
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromService:
          name: outline-db
          type: postgres
      - key: REDIS_URL
        fromService:
          name: outline-redis
          type: redis
      - key: URL
        value: https://ryco-outline.onrender.com
      - key: PORT
        value: 3000
      - key: FORCE_HTTPS
        value: "true"

  - type: postgres
    name: outline-db
    plan: standard
    region: oregon

  - type: redis
    name: outline-redis
    plan: standard
    region: oregon
